# nix/secrets.nix
#
# Reads SSH material from ./secrets/ for both the host (private SSH key,
# known_hosts) and the VMs (per-node host keys, user pubkey for
# authorized_keys). Generated by `nix run .#k8s-gen-secrets`.
#
# If ./secrets/ does not exist, returns nulls so the flake still
# evaluates — but `nix run .#k8s-start-all` will then fail because
# microvm.nix requires the per-node host key. Run k8s-gen-secrets
# first.
#
{ pkgs, lib }:
let
  secretsDir = ../secrets;
  hasSecrets = builtins.pathExists secretsDir;

  constants = import ./constants.nix;
in
if !hasSecrets then {
  k8sSecrets = null;
  sshPubKey = null;
  hostKeyPath = _: null;
  knownHostsPath = null;
  cephKeyringPath = null;
  cephClientSecret = null;
  cephConf = null;
}
else
let
  sshPubKeyFile = secretsDir + "/ssh-ed25519.pub";
  sshPubKey = if builtins.pathExists sshPubKeyFile
    then lib.trim (builtins.readFile sshPubKeyFile)
    else null;

  # Per-node sshd host private key, baked into the VM image at build
  # time. Activation script in nix/microvm.nix copies it to
  # /etc/ssh/ssh_host_ed25519_key with mode 0600.
  hostKeyPath = nodeName:
    let
      f = secretsDir + "/host-keys/${constants.getHostname nodeName}";
    in
    if builtins.pathExists f then f else null;

  knownHostsFile = secretsDir + "/known_hosts";
  knownHostsPath = if builtins.pathExists knownHostsFile
    then knownHostsFile
    else null;

  # ─── CephFS external-client material ─────────────────────────────
  # Generated by k8s-gen-secrets. The keyring file is baked into the
  # client microvm at build time; the secret is also exposed so the
  # ceph-external-client env module can drop it into a K8s Secret
  # that a one-shot Job reads to `ceph auth import` into the cluster.
  cephKeyringFile = secretsDir + "/cephfs-client.keyring";
  cephKeyringPath = if builtins.pathExists cephKeyringFile
    then cephKeyringFile
    else null;

  cephSecretFile = secretsDir + "/cephfs-client.secret";
  cephClientSecret = if builtins.pathExists cephSecretFile
    then lib.trim (builtins.readFile cephSecretFile)
    else null;

  # /etc/ceph/ceph.conf for the external client. MONs run on
  # hostNetwork so they advertise the node IPs directly — the list
  # is constants.ceph.monHosts (cp0/cp1/cp2 on port 6789, msgr-v1).
  cephConf = pkgs.writeText "ceph.conf" ''
    [global]
    mon_host = ${lib.concatStringsSep "," constants.ceph.monHosts}
  '';
in
{
  # No K8s Secret manifests to apply at bootstrap. The ceph-external-
  # client env module produces its own Secret from cephClientSecret
  # above using the inline-string manifest shape.
  k8sSecrets = null;
  inherit sshPubKey hostKeyPath knownHostsPath
          cephKeyringPath cephClientSecret cephConf;
}
