# nix/secrets.nix
#
# Reads SSH material from ./secrets/ for both the host (private SSH key,
# known_hosts) and the VMs (per-node host keys, user pubkey for
# authorized_keys). Generated by `nix run .#k8s-gen-secrets`.
#
# If ./secrets/ does not exist, returns nulls so the flake still
# evaluates — but `nix run .#k8s-start-all` will then fail because
# microvm.nix requires the per-node host key. Run k8s-gen-secrets
# first.
#
{ pkgs, lib }:
let
  secretsDir = ../secrets;
  hasSecrets = builtins.pathExists secretsDir;

  constants = import ./constants.nix;
in
if !hasSecrets then {
  k8sSecrets = null;
  sshPubKey = null;
  hostKeyPath = _: null;
  knownHostsPath = null;
}
else
let
  sshPubKeyFile = secretsDir + "/ssh-ed25519.pub";
  sshPubKey = if builtins.pathExists sshPubKeyFile
    then lib.trim (builtins.readFile sshPubKeyFile)
    else null;

  # Per-node sshd host private key, baked into the VM image at build
  # time. Activation script in nix/microvm.nix copies it to
  # /etc/ssh/ssh_host_ed25519_key with mode 0600.
  hostKeyPath = nodeName:
    let
      f = secretsDir + "/host-keys/${constants.getHostname nodeName}";
    in
    if builtins.pathExists f then f else null;

  knownHostsFile = secretsDir + "/known_hosts";
  knownHostsPath = if builtins.pathExists knownHostsFile
    then knownHostsFile
    else null;
in
{
  # No K8s Secret manifests to apply at bootstrap. Future ceph-related
  # offline secrets (e.g. a deterministic S3 access keypair) could be
  # added here following the source repo's runCommand + jq pattern.
  k8sSecrets = null;
  inherit sshPubKey hostKeyPath knownHostsPath;
}
